name: COM731
channels:
  - defaults
dependencies:
  - python=3.10
  - jinja2
  - matplotlib
  - pandas
  - tabulate
  - ipykernel
  - autopep8
  - conda-forge::openjdk
  - pip:
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.0
      - namex==0.0.8
      - optree==0.13.1
      - rich==13.9.4
